version: '3.8'

services:
  frontend:
    build:
      context: ./src  # или ./react-app — зависит от твоей структуры
    container_name: react-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  tileserver:
    image: klokantech/tileserver-gl
    container_name: tileserver-belarus
    volumes:
      - ./data:/data
    ports:
      - "8080:80"
    restart: unless-stopped
